### ISSUE TITLE
OpenStack instances not removed when network fails to attach

### ISSUE THREAD

**Issue by drew-viles** [eschercloudai/baski#37]
If the request to check the status of an instance comes back with "Instance network is not ready yet" then rather than waiting, trying again or failing gracefully, The code instead panics and the instance is left behind.

```
2023/04/14 11:12:53 waiting for the instance to come up before attaching an IP
2023/04/14 11:13:08 attaching IP xxx.xxx.xxx.xxx to the instance INSTANCE_ID
panic: Bad request with: [POST https://openstack.example.com:8774/v2.1/servers/INSTANCE_ID/action], error message
: {"badRequest": {"code": 400, "message": "Instance network is not ready yet"}}
goroutine 1 [running]:
github.com/eschercloudai/baski/pkg/openstack.attachFloatingIP(0xafbde0?, {0xc000150330, 0x24})
        /app/pkg/openstack/openstack.go:269 +0x3a5
github.com/eschercloudai/baski/pkg/openstack.(*Client).CreateServer(0xc00003bc00?, 0xc0003dc120, 0xc0001f2280)
        /app/pkg/openstack/openstack.go:180 +0x435
github.com/eschercloudai/baski/pkg/cmd/scan.NewScanCommand.func1(0xc0001fe900?, {0xbb9ebd?, 0x0?, 0x0?})
        /app/pkg/cmd/scan/scan.go:66 +0x1f8
github.com/spf13/cobra.(*Command).execute(0xc0001fe900, {0x113c0a8, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000005200)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/eschercloudai/baski/pkg/cmd.Execute(...)
        /app/pkg/cmd/root.go:57
main.main()
        /app/cmd/baski/main.go:31 +0x25
time="2023-04-14T11:13:09 UTC" level=info msg="sub-process exited" argo=true error="<nil>"
time="2023-04-14T11:13:09 UTC" level=warning msg="cannot save artifact /tmp/results.json" argo=true error="stat /tmp/results.json: no such file or directory"
Error: exit status 2
```

**Comment by drew-viles** [comment]
Fixed in #41 as part of improved error checking
